Repository scan-io-git/scan-io, pull requests merged in 2024-08, with the labels that each got.

#94 New configs, metadata, trufflehog3 plugin features
  cmd/analyse/analyse.go
  cmd/fetch/fetch.go
  cmd/integration-vcs/integration-vcs.go
  cmd/list/list.go
  config_example.yml
  internal/bitbucket/client.go
  internal/fetcher/fetcher.go
  internal/scanner/scanner.go
  internal/vcsintegrator/vcsintegrator.go
  pkg/shared/config/config.go
  pkg/shared/httpclient/client.go
  plugins/bitbucket/bitbucket.go
  plugins/trufflehog3/VERSION
  plugins/trufflehog3/internal/config.go
  plugins/trufflehog3/internal/report.go
  plugins/trufflehog3/internal/utils.go
  plugins/trufflehog3/trufflehog3.go
  plugins/trufflehog3/validation.go
Labels: enhancement

#98 Hot fix: write correct format of list results
  cmd/list/list.go
  internal/utils/utils.go
Labels: bug

#97 fix to-html locations for report with absolute paths
  cmd/to-html.go
  internal/sarif/sarif.go
  templates/tohtml/report.html
Labels: invalid
